Repository Susmita-Dey/Sukoon, pull requests merged in 2022-10, with the labels that each got.

#536 Let's explore button position improved
  css/style.css
  index.html
Labels: enhancement

#540 Changed scroll function names
  html/childTherapy.js
Labels: bug, hacktoberfest-accepted

#539 Fixed buttons for 'The Psychology of Money'
  html/readingTherapy.html
Labels: bug, hacktoberfest-accepted

#549 feature: Added issue-template
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/other.yml
Labels: documentation, enhancement, hacktoberfest-accepted

#552 Modified login page and improved frontend
  html/css/login.css
  html/login.html
Labels: enhancement, hacktoberfest-accepted

#544 added smooth scroll to reading and child therapy page
  css/childTherapy.css
  css/readingTherapy.css
  html/childTherapy.html
  index.html
Labels: enhancement, hacktoberfest-accepted

#543 Added more videos to talking therapy page
  html/talkingTherapy.html
Labels: enhancement, hacktoberfest-accepted

#555 feat: added pr template
  .github/.github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, enhancement, hacktoberfest-accepted

#547 docs: Fix Links in CONTRIBUTING.md and CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation, hacktoberfest-accepted

#561 Fixed right margin issue on Yoga page
  html/yogatherapy.html
Labels: bug, hacktoberfest-accepted

#558 Removed space in footer of all therapy pages
  css/audio.css
  css/readingTherapy.css
  css/talking.css
  css/yoga.css
  html/css/laugh.css
Labels: enhancement, hacktoberfest-accepted

#557 Added show/hide password button with functionality and back button
  html/css/login.css
  html/login.html
Labels: enhancement, hacktoberfest-accepted

#563 Added Benefits section to reading therapy page.
  css/readingTherapy.css
  html/readingTherapy.html
Labels: enhancement, hacktoberfest-accepted
