Repository Susmita-Dey/Sukoon, pull requests merged in 2022-09, with the labels that each got.

#341 Fixed the therapy pages
  css/readingTherapy.css
  css/style.css
  css/talking.css
  css/yoga.css
  html/audioTherapy.html
  html/contact.html
  html/css/laugh.css
  html/laughTherapy.html
  html/readingTherapy.html
  index.html
Labels: ssoc-2022, intermediate

#307 Duplicate Fix Issue: #167 : Improving the responsiveness of home page
  css/style.css
  html/yogatherapy.html
  index.html
Labels: bug, duplicate, ssoc-2022

#360 Fix Issue: #339 Navbar on Audio Therapy has issues
  css/audio.css
  html/audioTherapy.html
Labels: ssoc-2022, intermediate

#366 Added a transition to the buttons Aasanas on Yoga Therapy Page
  css/yoga.css
Labels: enhancement, ssoc-2022, intermediate

#369 Made faq text responsive
  css/style.css
Labels: enhancement, ssoc-2022, intermediate

#362 Fix Issue: #310 Changing the design of the Navbar on Yoga therapy page and also fixing its position
  css/yoga.css
  html/yogatherapy.html
Labels: enhancement, ssoc-2022, intermediate

#352 Fix Issue: #333 Added a blur filter in the background of the Home page navbar.
  css/style.css
  index.html
Labels: ssoc-2022, intermediate

#378 Improved the navbar of laughing therapy
  html/css/laugh.css
  html/laughTherapy.html
Labels: enhancement, ssoc-2022, intermediate

#372 Made the footer of therapy pages similar to Home page
  css/audio.css
  css/readingTherapy.css
  css/style.css
  css/talking.css
  css/yoga.css
  html/audioTherapy.html
  html/css/laugh.css
  html/laughTherapy.html
  html/readingTherapy.html
  html/talkingTherapy.html
  html/yogatherapy.html
Labels: enhancement, ssoc-2022, intermediate

#382 Changing font style
  css/style.css
Labels: enhancement, beginner, ssoc-2022

#384 Updated README.md
  README.md
Labels: documentation, beginner, ssoc-2022

#394 Improved member card UI
  css/style.css
Labels: enhancement, ssoc-2022, intermediate

#395 Scrollbar fix
  css/style.css
  index.html
Labels: enhancement, ssoc-2022, intermediate

#393 added videos to laughing therapy page
  html/laughTherapy.html
Labels: enhancement, ssoc-2022, intermediate

#400 Changes in Redme
  README.md
Labels: documentation, enhancement, beginner, ssoc-2022

#399 Fix the "X" sign on Talking Therapy page
  css/talking.css
Labels: bug, beginner, ssoc-2022

#403 added text in about section
  css/style.css
  images/about.jpg
  index.html
Labels: enhancement, ssoc-2022, intermediate

#404 made the audiobooks open in new tab
  html/audioTherapy.html
Labels: enhancement, ssoc-2022, intermediate

#432 shifted the presentation ppt and pdf into docs folder
  docs/presentation.pdf
  docs/presentation.pptx
Labels: documentation, beginner, ssoc-2022

#429 Animation on Scrolling has been added.
  css/talking.css
  html/audioTherapy.html
  html/css/contact.css
  html/laughTherapy.html
  html/login.html
  html/talkingTherapy.html
  images/Spin-Preloader-1.gif
  index.html
Labels: enhancement, ssoc-2022, advanced

#398 Fix Issue #361 Improving the design of the mobile layout navbar menu on home page
  css/style.css
  index.html
  js/index.js
Labels: enhancement, ssoc-2022, advanced

#476 Made Child-therapy page
  css/childTherapy.css
  html/childTherapy.html
  html/childTherapy.js
  images/about-child.jpg
  images/child.jpg
  images/slider-2.jpg
  images/slider-3.jpg
  images/slider-4.jpg
  images/slider-5.jpg
  images/slider-6.jpg
  images/slider-7.jpg
  images/slider-8.jpg
  images/slider-9.jpg
  images/slider1.jpg
Labels: enhancement, ssoc-2022, advanced

#481 Added new services to FAQ
  index.html
Labels: enhancement, ssoc-2022, intermediate

#449 made font-size, font family of all headings on home page similar
  css/style.css
  index.html
Labels: enhancement, ssoc-2022, intermediate

#430 Added 2 more audio books to audio therapy
  html/audioTherapy.html
Labels: enhancement, ssoc-2022, intermediate

#470 Issue #437 Fixed.
  html/css/laugh.css
  html/laughTherapy.html
Labels: bug, ssoc-2022, intermediate

#482 Fixed the alignment of lets explore button
  css/style.css
Labels: enhancement, ssoc-2022, intermediate

#415 fixed the navbar of talking therapy page
  html/talkingTherapy.html
Labels: bug, ssoc-2022, intermediate

#478 Initializing animate on scroll AOS in the app
  html/audioTherapy.html
  html/laughTherapy.html
  html/readingTherapy.html
  html/talkingTherapy.html
  html/yogatherapy.html
Labels: enhancement, ssoc-2022, advanced

#453 Enhanced the FAQ Section
  css/style.css
  html/css/contact.css
  html/css/laugh.css
  html/laughTherapy.html
  html/readingTherapy.html
  index.html
  js/index.js
Labels: enhancement, ssoc-2022, advanced

#492 Pre-Loader has been added.
  css/audio.css
  css/readingTherapy.css
  css/talking.css
  css/yoga.css
  html/audioTherapy.html
  html/childTherapy.html
  html/contact.html
  html/css/contact.css
  html/css/laugh.css
  html/css/login.css
  html/laughTherapy.html
  html/login.html
  html/readingTherapy.html
  html/talkingTherapy.html
  html/yogatherapy.html
Labels: enhancement, ssoc-2022, advanced

#401 Fix Issue: #367 Improving the Responsiveness of the Yoga Therapy Page And Enhancing the design.
  css/yoga.css
  html/yogatherapy.html
Labels: enhancement, ssoc-2022, advanced

#501 Add the 3D books to the Reading Therapy Section
  css/readingTherapy.css
  html/laughTherapy.html
  html/readingTherapy.html
Labels: enhancement, ssoc-2022, advanced

#489 Fixed #488: Updated 'contributing.md'.
  CONTRIBUTING.md
Labels: enhancement, beginner, ssoc-2022

#495 Updated Testimonial section
  css/style.css
  images/Kelvin Parmar.jpg
  images/Mohit.jpg
  images/Shravani Kaware.jpg
  images/vanshita.jpg
  index.html
Labels: enhancement, ssoc-2022, intermediate

#515 fix#485: get started section for new contributors
  README.md
Labels: documentation, beginner, ssoc-2022

#509 Top-Down Button has been added in all other sub-pages of website
  css/audio.css
  css/readingTherapy.css
  css/talking.css
  css/yoga.css
  html/audioTherapy.html
  html/css/laugh.css
  html/laughTherapy.html
  html/readingTherapy.html
  html/talkingTherapy.html
  html/yogatherapy.html
Labels: ssoc-2022, intermediate, assigned

#497 added new services to footer of every page
  html/audioTherapy.html
  html/childTherapy.html
  html/laughTherapy.html
  html/readingTherapy.html
  html/talkingTherapy.html
  html/yogatherapy.html
  index.html
Labels: enhancement, beginner, ssoc-2022

#502 Added "Home" to the navbar
  index.html
Labels: enhancement, beginner, ssoc-2022

#519 Added animation to the laugh thereapy page Issue #467
  html/laughTherapy.html
Labels: ssoc-2022, advanced, assigned

#420 Fix Issue: #407 Implementing a custom scroll bar on all pages.
  css/audio.css
  css/readingTherapy.css
  css/style.css
  css/talking.css
  css/yoga.css
  html/css/laugh.css
Labels: enhancement, ssoc-2022, advanced

#421 Fix Issue: #408 Adding new services section on the home page.
  css/style.css
  images/child.jpg
  images/speicaltherapy.jpg
  images/spiritualtherapy.jpg
  index.html
Labels: enhancement, ssoc-2022, intermediate

#525 Fixed issue on child therapy background image
  css/childTherapy.css
  images/childbg.jpg
  index.html
Labels: bug, beginner, ssoc-2022

#527 Added the animation to the about section #467
  index.html
Labels: enhancement, ssoc-2022, intermediate

#531 Added transition to the talking thereapy page #465
  html/talkingTherapy.html
Labels: enhancement, ssoc-2022, intermediate

#529 fixed meet our members section
  css/style.css
  index.html
Labels: bug, ssoc-2022, intermediate

#524 Fix Issue: #411 Improving the responsiveness of the laughing therapy page.
  html/css/laugh.css
  html/laughTherapy.html
Labels: enhancement, ssoc-2022, intermediate

#473 Title tag added (Fixes #456)
  css/readingTherapy.css
  html/audioTherapy.html
  html/comingSoon.html
  html/contact.html
  html/css/laugh.css
  html/laughTherapy.html
  html/login.html
  html/readingTherapy.html
  html/talkingTherapy.html
  html/yogatherapy.html
  index.html
Labels: enhancement, ssoc-2022, intermediate

#530 changed background of faq section
  css/style.css
  index.html
Labels: enhancement, ssoc-2022, intermediate

#533 Fix Issue: #410 Make the about us section on home page responsive
  css/style.css
  index.html
Labels: enhancement, ssoc-2022, intermediate
