Repository Susmita-Dey/Sukoon, pull requests merged in 2022-08, with the labels that each got.

#67 ⬆️ added back top button
  index.html
  js/index.js
Labels: enhancement, beginner, ssoc-2022

#59 reading therapy
  css/readingTherapy.css
  html/readingTherapy.html
  index.html
Labels: enhancement, ssoc-2022, advanced

#104 added transition of 0.3s in .responsive a button
  css/style.css
Labels: beginner

#117 Fixed the "Donate" link
  index.html
Labels: enhancement, beginner, ssoc-2022

#120 Fixed the Code of Conduct Link
  index.html
Labels: bug, beginner, ssoc-2022

#112 added CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, beginner, ssoc-2022

#131 Changed the design of the coming soon page issue #96
  css/styles.css
  html/comingSoon.html
  images/handyman.png
Labels: enhancement, ssoc-2022, intermediate

#102 issue #81
  html/css/login.css
  html/login.html
Labels: ssoc-2022, advanced

#137 Fixed the title of reading therapy website issue #136
  html/readingTherapy.html
Labels: beginner, ssoc-2022

#128 Added login button
  css/style.css
  index.html
Labels: beginner, ssoc-2022

#139 Added signup page.
  html/css/signup.css
  html/signup.html
Labels: enhancement, ssoc-2022, advanced

#144 Improving the Heading Font Family & Font Size of About Us Section
  css/style.css
  index.html
Labels: enhancement, beginner, ssoc-2022

#133 Made the services section responsive
  css/style.css
Labels: bug, ssoc-2022, intermediate

#146 Improved UI on audio Page
  css/audio.css
  html/audioTherapy.html
Labels: enhancement, ssoc-2022, advanced

#150 Update footer with new logo
  css/style.css
  images/footerlogo.png
  index.html
Labels: enhancement, beginner, ssoc-2022

#161 updated logo.png
  logo.png
Labels: enhancement, beginner, ssoc-2022

#160 Audiobook's card Improvement
  css/audio.css
  html/audioTherapy.html
Labels: enhancement, ssoc-2022, intermediate

#164 Fixed login button
  css/style.css
  index.html
Labels: bug, beginner, ssoc-2022

#173 solved button cursor problem
  css/style.css
Labels: beginner, ssoc-2022

#179 Testimonials
  css/style.css
  index.html
Labels: enhancement, ssoc-2022, advanced

#155 Fixes issue #116
  css/audio.css
  html/audioTherapy.html
Labels: enhancement, ssoc-2022, intermediate

#174 Give Responsiveness to heading of about section
  css/style.css
Labels: bug, ssoc-2022, intermediate

#191 Fixed the link in logo of Audio therapy
  html/audioTherapy.html
Labels: bug, beginner, ssoc-2022

#196 Added validation to signup form using html attribute
  html/signup.html
Labels: enhancement, beginner, ssoc-2022

#198 Changed the design of the reading therapy page
  css/readingTherapy.css
  html/readingTherapy.html
  images/inspiration (1).png
  images/inspiration.png
  images/job-satisfaction.png
  images/motivation (1).png
  images/motivation (3).png
  images/motivation.png
  images/passion.png
  images/reading1.png
  images/woman (1).png
Labels: ssoc-2022, intermediate

#199 Updated text in FAQ section
  index.html
Labels: beginner, ssoc-2022

#203 Improve the font family of FaQ Section
  css/style.css
Labels: enhancement, beginner, ssoc-2022

#208 Fix Issue #167 : Improving the responsiveness of home page
  css/style.css
  index.html
Labels: enhancement, ssoc-2022, intermediate, assigned

#213 Added more questions to the faq section related to the services
  index.html
Labels: beginner, ssoc-2022

#214 Yoga therapy page Issue Number #66
  css/yoga.css
  html/yogatherapy.html
  images/yoga1.webp
  images/yoga2.webp
  images/yoga3.webp
  images/yoga4.webp
  images/yoga5.webp
  index.html
Labels: enhancement, ssoc-2022, advanced

#246 Fixed logo-link in talking therapy
  html/talkingTherapy.html
Labels: bug, beginner, ssoc-2022

#242 Fixed the "Videos" nav-link in talking therapy
  html/talkingTherapy.html
Labels: bug, beginner, ssoc-2022

#240 Improved the Login button
  css/style.css
Labels: enhancement, ssoc-2022, intermediate

#235 Added Preloader
  css/style.css
  index.html
Labels: enhancement, ssoc-2022, advanced

#251 Hyperlinked the sevices to their respective page on footer section
  index.html
Labels: bug, beginner, ssoc-2022

#237 updated login/signup page
  html/css/login_2.css
  html/login_2.html
  images/signupill.png
  index.html
Labels: enhancement, ssoc-2022, advanced

#257 Designed new scroll bar
  css/style.css
  index.html
Labels: enhancement, ssoc-2022, intermediate

#259 Service Section
  css/style.css
Labels: enhancement, ssoc-2022, intermediate

#217 Update README.md
  README.md
Labels: documentation, beginner, ssoc-2022

#218 Add Website link in Readme.
  README.md
Labels: documentation, beginner, ssoc-2022

#256 Fixes #252
  css/style.css
  index.html
Labels: beginner, ssoc-2022

#262 Fixes #260
  css/readingTherapy.css
Labels: enhancement, beginner, ssoc-2022

#266 Update audioTherapy.html
  html/audioTherapy.html
Labels: enhancement, beginner, ssoc-2022

#264 Improved the login and sign up button in login/signup page.
  html/css/login_2.css
  html/login_2.html
Labels: enhancement, ssoc-2022, intermediate

#166 Fix Issue: #147 - Making the navbar on Audio page responsive
  css/audio.css
  html/audioTherapy.html
Labels: enhancement, ssoc-2022, intermediate

#224 Header section UI fixed
  css/style.css
Labels: bug, ssoc-2022, intermediate

#244 Fix Issue : #221 - Improving responsiveness and Navbar design on Talking Therapy page.
  css/talking.css
  html/talkingTherapy.html
Labels: enhancement, ssoc-2022, advanced

#271 made the login/SignUp page responsive
  html/css/login_2.css
  index.html
Labels: bug, ssoc-2022, intermediate

#272 Coming soon page updated
  css/s2.css
  css/style.css
  css/styles.css
  html/comingSoon.html
  images/coming_soon_bg.png
  index.html
  js/script.js
Labels: enhancement, ssoc-2022, advanced

#292 Fixed the position of the overlapping button in audiobooks section
  css/audio.css
  html/audioTherapy.html
Labels: enhancement, beginner, ssoc-2022

#293 Made laughing therapy page
  html/css/laugh.css
  html/laughTherapy.html
  images/laugh.jpg
  images/laughing.jpg
  images/meme1.jpg
  images/meme2.jpg
  images/meme3.jpg
  images/meme4.jpg
  images/meme5.jpg
  images/meme6.jpg
  index.html
Labels: enhancement, ssoc-2022, advanced

#311 Fixed Overlapping Content in Reading Therapy
  css/readingTherapy.css
Labels: bug, ssoc-2022, intermediate

#314 Improved Read btn in reading therapy
  css/readingTherapy.css
  html/readingTherapy.html
Labels: enhancement, ssoc-2022, advanced

#324 punctuation corrected issue #321
  index.html
Labels: beginner, ssoc-2022

#325 Made the navbar of reading therapy page responsive
  css/readingTherapy.css
  html/readingTherapy.html
Labels: enhancement, ssoc-2022, intermediate

#323 Site has been made converted to PWA (Fixes issue #312)
  css/style.css
  index.html
  manifest.json
  offline.html
  serviceworker.js
Labels: enhancement, ssoc-2022, advanced

#326 Contact fix
  css/style.css
  html/contact.html
  index.html
Labels: bug, ssoc-2022, intermediate

#284 Footer added
  css/audio.css
  css/readingTherapy.css
  css/talking.css
  css/yoga.css
  html/audioTherapy.html
  html/css/laugh.css
  html/laughTherapy.html
  html/readingTherapy.html
  html/talkingTherapy.html
  html/yogatherapy.html
  index.html
Labels: enhancement, ssoc-2022, intermediate

#286 Improved the width of Image & visibility of points in Yoga Therapy Page
  css/readingTherapy.css
  css/yoga.css
  html/css/login_2.css
  html/yogatherapy.html
Labels: ssoc-2022, intermediate

#332 Fix Issue: #269 : Improving the design of accordian when open.
  css/style.css
  index.html
Labels: enhancement, ssoc-2022, intermediate
