Repository Susmita-Dey/Sukoon, pull requests merged in 2023-10, with the labels that each got.

#621 Hide the 'Show Password' button on the right side of the password input box in different browsers
  html/login.html
Labels: bug

#615 Update documentation: expanded on the provided services
  README.md
Labels: documentation, enhancement, good first issue, beginner

#622 Loginalert
  html/contact.html
  html/login.html
  html/yogatherapy.html
  index.html
Labels: bug, enhancement

#616 Fixed issue#611
  index.html
Labels: enhancement, good first issue

#614 Fixed alignment of member section when screen size is decreased
  css/style.css
Labels: enhancement

#612 Fixed the Issue with Mobile Responsiveness
  html/css/login.css
  html/login.html
Labels: bug, enhancement

#610 [FIX] ChildTherapy Video Section
  css/childTherapy.css
  html/childTherapy.html
Labels: enhancement

#609 childTherapy Navbar backdrop filter appears onScroll
  css/childTherapy.css
  html/childTherapy.html
  html/childTherapy.js
Labels: enhancement

#605 fixe: #599 solved empty data getting submitted issue
  html/contact.html
Labels: enhancement

#626 Login page password display issue
  html/login.html
Labels: bug
