Repository Susmita-Dey/Sukoon, pull requests merged in 2023-07, with the labels that each got.

#601 Service card bottom padding
  CONTRIBUTING.md
  css/style.css
Labels: enhancement

#568 Fixed Navbar Link hiding Section Titles they point to
  css/style.css
Labels: enhancement

#569 Fix various typos in site content and whitespace in HTML tags.
  html/audioTherapy.html
  html/childTherapy.html
  html/laughTherapy.html
  html/readingTherapy.html
  html/spirituality.html
  html/talkingTherapy.html
  html/yogatherapy.html
  index.html
Labels: documentation, enhancement, beginner

#582 added a necessary space
  index.html
Labels: documentation, beginner

#590 :bug: : image expand issue
  style.css
Labels: enhancement

#593 add: missing space in stressfree
  index.html
Labels: beginner

#591 spirituality page reposnivness fix
  css/spirituality.css
  html/spirituality.html
Labels: enhancement, intermediate

#602 fix: change PR template path
  .github/pull_request_template.md
Labels: bug, documentation
